CONFIG_URL = "abc"
ConfigUrl = ""

[Http]
DangerousAutoWhitelist = true
CORES = "*"
JwtSecret = "DhSQekDq1XctftfH5LnX6V5pmJMTaOOM"
MaxBufferSize = 10485760
Path = "/"
Port = 81

[[HttpRPC]]
Jwt = "ther's no such jwt"
Name = "doptime"
UrlBase = "https://api.doptime.com"

[[Redis]]
DB = 0
Host = "aircraft.lan"
Name = "default"
Password = "XWkHqup04Gcm7Plieh5x"
Port = 6379
Username = ""

# [[Redis]]
# DB = 2
# Host = "keydb.lan"
# Name = "def6379"
# Password = "mXJLFAt3y47woLF5AkNiKs3ug1D0yWz8"
# Port = 6379
# Username = ""

[Settings]
LogLevel = 1
SUToken = "HboVsNf0bMa1fYq9HXr02SaRD7yz3gyj"

[[EvoRealms]]
Name = "RedisDB"
Enable = false
RootPath = "/Users/yang/doptime/redisdb"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum"
SkipDirs = "doc,.git,.idea,.vscode,.evolab"

[[EvoRealms]]
Name = "doptimeutils"
Enable = false
RootPath = "/Users/yang/doptime/doptime/utils"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum,.excalidraw,.png,.mdx,*.go"
SkipDirs = ".git,.idea,.vscode,3rd_lang,DockerFile,test,.evolab,vars,"

[[EvoRealms]]
Name = "doptime"
Enable = false
RootPath = "/Users/yang/doptime/doptime"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum,.excalidraw,.png,.mdx"
SkipDirs = ".git,.idea,.vscode,3rd_lang,DockerFile,test,.evolab,vars,"

[[EvoRealms]]
Name = "aircraft"
Enable = false
RootPath = "/Users/yang/aircraft"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum"
SkipDirs = ".git,.idea,.vscode,.evolab"

[[EvoRealms]]
Name = "aircraftwing"
Enable = false
RootPath = "/Users/yang/aircraft/wing"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum,expired_ideas.md"
SkipDirs = ".git,.idea,.vscode,.evolab"

[[EvoRealms]]
Name = "btctrade"
Enable = false
RootPath = "/Users/yang/btctrade"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum,expired_ideas.md"
SkipDirs = ".git,.idea,.vscode,.evolab,.ignored"

[[EvoRealms]]
Name = "learniverse"
Enable = false
RootPath = "/Users/yang/learniverse"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum,expired_ideas.md"
SkipDirs = ".git,.idea,.vscode,.evolab,.ignored"

[[EvoRealms]]
Name = "doptime-client"
Enable = true
RootPath = "/Users/yang/doptime/doptime-client"
SkipFiles = ".DS_Store,.gitignore,.mod,.sum,package-lock.json"
SkipDirs = ".git,.idea,.vscode,.evolab,.ignored,node_modules,lib"

